// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShortcutWindow
{
    internal sealed partial class Vsix
    {
        public const string Id = "ShortcutWindow.d11ce83f-99f9-41f5-8c58-9e5c4286fd2c";
        public const string Name = "Shortcut Presenter";
        public const string Description = @"Shows what keyboard shortcuts are being used in the corner of the screen. Great for presentations and demos";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "keyboard, shortcut, presentation";
    }
}
